services:
  backend:
    image: mirttgg/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/staticfiles/ # Папка для сбора статики Django
      - media_value:/app/media/       # Папка для медиа-файлов
    depends_on:
      - db
    env_file:
      - ./.env # Убедись, что на сервере есть .env файл с секретами

  frontend:
    image: mirttgg/foodgram_frontend:latest
    volumes:
      - ./frontend_build:/usr/share/nginx/html/ # Сюда Nginx будет смотреть за файлами React

  nginx:
    image: mirttgg/foodgram_nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend_build:/usr/share/nginx/html/             # 1. Монтируем фронтенд
      - static_value:/var/html/static/                      # 2. Монтируем статику Django
      - media_value:/var/html/media/                        # 3. Монтируем медиа Django
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf   # 4. Монтируем сам конфиг Nginx
    depends_on:
      - backend

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
  db_value:
