services:
  backend:
    image: mirttgg/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/media/
    depends_on:
      - db:
          condition: service_healthy
    env_file:
      - ./.env

  # frontend-образ больше не нужен в docker-compose, так как nginx его заменяет
  # frontend:
  #   image: mirttgg/foodgram_frontend:latest
  #   volumes:
  #     - ./frontend_build:/usr/share/nginx/html/

  nginx:
    image: mirttgg/foodgram_nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      # СТАРЫЙ, НЕПРАВИЛЬНЫЙ ПУТЬ: - ./frontend_build:/usr/share/nginx/html/
      # Так как у нас нет сбилженного фронтенда на сервере, а он внутри образа nginx,
      # нам нужно монтировать только статику Django и сам конфиг Nginx.
      # Папка с фронтендом уже "запечена" в образ mirttgg/foodgram_nginx:latest
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # <-- ИСПРАВЛЕНО
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      # Эта команда проверяет, готова ли база данных принимать подключения
      test: ["CMD-SHELL", "pg_isready -U ${{POSTGRES_USER}} -d ${{POSTGRES_DB}}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  static_value:
  media_value:
  db_value:
